const routes = {
  mainBlock: '/',
  aboutBlock: '/about',
  contacts: '/contacts',

  newsBlock: '/news',
  detailedNewsMain: '/news/:id',

  equipment: '/equipment',
  webCenterMain: '/equipment/webCenterBerlio',
  oilAndCapitalMain: '/equipment/oilAndCapital',
  selfServiceCheckoutMain: '/equipment/selfServiceCheckout',
  gsAutomationSystemMain: '/equipment/gsAutomationSystem',
  invoicesSiteMain: '/equipment/invoicesSite',
  invoicesSiteTariffsMain: '/equipment/invoicesSiteTariffs',
  berlioInternetClientAppMain: '/equipment/berlioInternetClientApp',
  berlioCardPayAppMain: '/equipment/berlioCardPayApp',
  smartPayAppMain: '/equipment/smartPayApp',
  personalAccWebAppMain: '/equipment/personalAccWebApp',

  forClientsMain: '/clients',
  serviceInEPSMain: '/clients/serviceInEPS',
  forFuelPayments: '/clients/forFuelPayments',
  signAndResignMain: '/clients/signAndResign',
  gettingCardMain: '/clients/gettingElectronicCard',
  dealResignationMain: '/clients/dealResignation',
  priceListsAndTariffsMain: '/clients/priceListsAndTariffs',
  workWithPrivateAccountMain: '/clients/workWithPrivateAccount',
  documentsForDownloadMain: '/clients/documentsForDownload',
  cardUsageRulesMain: '/clients/cardUsageRules',
  plasticCardUsageRulesMain: '/clients/plasticCardUsageRules',
  nonResidentsSupportMain: '/clients/nonResidentsSupport',
  tollRoadsMain: '/clients/tollRoads',
  issuerRulesMain: '/clients/issuerRules',
  eMoneyRegulationsMain: '/clients/eMoneyRegulations',
  legislationMain: '/clients/legislation',
  reportIFRMain: '/clients/reportIFR',
  localActsInEPSMain: '/clients/localActsInEPS',

  forPartnersMain: '/partners',
  voiceRefServiceMain: '/partners/voiceRefService',
  loyaltyProgramMain: '/partners/loyaltyProgram',
  partnersDocumentsMain: '/partners/documentsForDownload',
  systemRulesMain: '/partners/systemRules',
  forBankInformationMain: '/partners/forBankInformation',
  partnersCardUsageRulesMain: '/partners/cardUsageRules',
  partnersPlasticCardUsageRulesMain: '/partners/plasticCardUsageRules',
  forNotAResidentsServicesMain: '/partners/forNotAResidentsServices',

  privacyMain: '/privacy',
  cookieConsentPolicy: '/privacy/cookie-consent-policy',
  buyersPolicy: '/privacy/buyers-policy',
  b2bPolicy: '/privacy/b2b-policy',
  applicantsPolicy: '/privacy/applicants-policy',

  pppsaPresentation: '/presentations/pppsa',
};

export default routes;
